services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "9999:3000"
    environment:
      - NODE_ENV="production"
    volumes:
      - /home/ubuntu/running/logs/freecodecamp-filemetadata:/program/logs