openapi: 3.0.3

info:
  title: File Metadata Microservice
  description: Solution of a freecodecamp task for creating a file metadata microservice.
  contact:
    email: jakusienko@gmail.com
  license:
    name: MIT
    url: https://en.wikipedia.org/wiki/MIT_License
  version: 1.1.0

externalDocs:
  url: https://www.freecodecamp.org/learn/back-end-development-and-apis/back-end-development-and-apis-projects/url-shortener-microservice
  description: FreeCodeCamp

servers:
  - url: https://filemetadata.profresor.net

paths:
  /api/fileanalyse:
    post:
      tags:
        - endpoints
      summary: File metadata
      description: "Upload a file and get its metadata. NOTE: If file is bigger than 10MB and has wrong extension (mainly executable types) endpoint may enter endless pending, refer to README link up top."
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/METADATA"

        400:
          description: Provided file missing or incorrect
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                FileTooLarge:
                  summary: File too large
                  value:
                    error: File size exceeds limit of 10MB
                InvalidExtension:
                  summary: Invalid file extension
                  value:
                    error: File type not allowed
                TwoExtensions:
                  summary: File has two or more extensions
                  value:
                    error: File name contains more than one extension
                NoFile:
                  summary: No file provided
                  value:
                    error: No file uploaded
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              example:
                error: "Internal server error"

  /api/hello:
    get:
      tags:
        - endpoints
      summary: API says hello
      description: Test endpoint to see if the API is running
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  greeting:
                    type: string
                example:
                  greting: "hello API"
      
components:
  schemas:
    METADATA:
      type: object
      properties:
        name:
          type: string
        type:
          type: string
        size:
          type: integer
      example:
        name: "example.txt"
        type: "text/plain"
        size: 12345
        